version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Migrate database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  run:
    aliases:
      - run
    desc: "Run the sso application"
    cmds:
      - go run ./cmd/sso/main.go
  test-migrate:
    aliases:
      - test-migrate
    desc: "Run database migration for testing"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
