version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Migrate database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  run:
    aliases:
      - run
      - run-local
      - local
    desc: "Run the sso application"
    cmds:
      - go run ./cmd/sso/main.go --config=./config/local.yaml
  test:
    aliases:
      - test-migrate
      - tests
      - test
    desc: "Run database migration for testing and run tests"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test && go test ./tests/ -v
